### ISSUE TITLE
GROUP_CONCAT and CASE WHEN

### ISSUE THREAD

**Issue by popovsergiy** [orocrm/doctrine-extensions#25] opened 2016-09-24 17:30 UTC
I have in my project expression like this ```new \Doctrine\ORM\Query\Expr\Select('GROUP_CONCAT(CASE WHEN serial.cartItem > 0 THEN serial.number ELSE 0 END)')``` which throw exception **[Syntax Error] line 0, col 130: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got '.'**. But the same expression with ```SUM``` function works correct ```new \ORM\Query\Expr\Select('SUM(CASE WHEN serial.cartItem > 0 THEN serial.number ELSE 0 END)')```. Native query with ```GROUP_CONCAT``` also works correct.

**Comment by x86demon** [comment] 2016-09-24 20:35
Hi, Sergey. Please describe what results do you expect.

**Comment by popovsergiy** [comment] 2016-09-25 14:08
If examine native query
```
SELECT
	c0_.id AS id_0,
	c1_.id AS id_1,
	r2_. CODE AS code_2,
    GROUP_CONCAT(r3_.number) serial_all,
    GROUP_CONCAT(CASE WHEN r3_.cartItemId > 0 THEN r3_.number END) serial_selected,
	r2_.sku AS sku_6,
	r2_. NAME AS name_7,
	c0_.quantity AS quantity_8,
	c0_.price AS price_9,
	r3_.*
FROM
	cart_item c0_
LEFT JOIN cart c1_ ON c0_.cartId = c1_.id
LEFT JOIN ra_spare_city r5_ ON (c0_.itemId = r5_.id)
LEFT JOIN ra_spare r2_ ON r5_.productId = r2_.id
LEFT JOIN ra_spare_serial r3_ ON r2_.id = r3_.productId AND (c0_.id = r3_.cartItemId OR r3_.cartItemId IS NULL)
WHERE
	c0_.cartId = 1777
GROUP BY r2_.id
```
this query in ```GROUP_CONCAT``` should give me only cartItem which bind in ```serial``` table otherwise nothig to do. At [screencast](http://screencast.com/t/zNkbtweKC) you can see **serial_selected** which has only one value and **serial_all** which include all avaliable values.

**Comment by x86demon** [comment] 2016-09-26 13:45
Hi, @popovsergiy 
Seems that this issue is duplicate of #19 

Checked it with next query
```
SELECT GROUP_CONCAT(CASE WHEN f.budget > 0 THEN f.budget ELSE 0 END) FROM Oro\\Entities\\Foo f GROUP BY f.code
```
Which works fine with latest release https://github.com/orocrm/doctrine-extensions/releases/tag/1.0.12

Please, check that you are using correct one

**Closed** 2016-09-26 13:47 UTC
Labels: duplicate
